name: Release and Publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: lvjiaxuan/github-action-templates/.github/workflows/pnpm-ni.yml@main
    with:
      run_script: nr lvr release
    secrets: inherit

  publish:
    uses: lvjiaxuan/github-action-templates/.github/workflows/pnpm-ni.yml@main
    with:
      run_script: nr lvr publish --sync-cnpm
    secrets: inherit
