name: Release and Publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: lvjiaxuan/github-action-templates/.github/workflows/lvr-release.yml@main
    secrets: inherit

  publish:
    # uses: lvjiaxuan/github-action-templates/.github/workflows/publish.yml@main
    uses: lvjiaxuan/github-action-templates/.github/workflows/pnpm-ni.yml@main
    with:
      install: true
      run_script: nr lvr publish --sync-cnpm
    secrets: inherit
