name: Release and Publish

on:
  push:
    tags:
      - v*

jobs:
  release_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup
        run: |
          pnpm config set auto-install-peers=true
          pnpm i -g @antfu/ni

      - name: Create a release and Publish to npmjs
        run: |
          nci
          nr build
          nr lvr release
          pnpm publish --access public --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
