name: Update Dependencies

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * FRI

jobs:
  update-deps:
    uses: lvjiaxuan/github-action-templates/.github/workflows/update-deps.yml@main
    with:
      email: 11309921+lvjiaxuan@users.noreply.github.com
      args: -x unconfig
